[project]
name = "agents"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "crewai>=0.114.0",
    "crewai-tools>=0.40.1",
    "ipykernel>=6.29.5",
    "litellm>=1.60.2",
    "nbformat>=5.10.4",
    "python-dotenv>=1.1.0",
    "ruff>=0.11.6",
]
